package shared.protocol;

public enum RequestType {
    REGISTER,
    LOGIN,
    LOGOUT,
    GET_PROFILE,
    UPDATE_PROFILE,
    CREATE_TWEET,
    DELETE_TWEET,
    SYNC_SOCIAL,
    CREATE_POST,
    CREATE_REPLY,
    CREATE_QUOTE,
    TOGGLE_LIKE,
    TOGGLE_REPOST,
    TOGGLE_BOOKMARK,
    TOGGLE_FOLLOW,
    MARK_NOTIFICATIONS_READ,
    PING,
}
